version: "3.8"
services:
  postgres:
    container_name: postgres_quiz-online
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: root
      POSTGRES_DB: QuizDB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_quiz-online
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: quiz@just.edu.so
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"